fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    view:
        view_response_listener:  'force'
        formats:
            json: true
    exception:
        enabled : true
        exception_controller: 'fos_rest.exception.controller:showAction'
    format_listener:
        rules:
            - { path: ^/,fallback_format: json, priorities: [ json ] }
