security:
    encoders:
        App\Entity\User:
            algorithm: argon2i
        App\Entity\Merch:
            algorithm: argon2i


    providers:
        chain_provider:
            chain:
                providers: [app_merch_provider, app_user_provider]

        # used to reload user from session & other features (e.g. switch_user)
        app_merch_provider:
            entity:
                class: App\Entity\Merch
                property: code

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email


        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_user:
            pattern:  ^/api/login
            provider: app_user_provider
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check_user
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        login_merch:
            pattern:  ^/api/merch
            provider: app_merch_provider
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/merch/login_check_merch
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true


    # access_control:
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     - { path: ^/profile, roles: ROLE_USER }

    access_control:
      #  - { path: ^/validator, roles: ROLE_VALIDATOR }
       # - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/merch, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }


