vich_uploader:
    db_driver: orm

        # mappings:
        #    perso_image:
        #        uri_prefix: /images/perso
        #         upload_destination: '%kernel.project_dir%/public/images/perso'

    mappings:
        merchs_image:
            uri_prefix: /images/merchs
            upload_destination: '%kernel.project_dir%/public/images/merchs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true




    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
