<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190905132723 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE age (id INT AUTO_INCREMENT NOT NULL, age VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, superficie_id INT DEFAULT NULL, emplacement_id INT DEFAULT NULL, environnement_id INT DEFAULT NULL, type_de_quartier_id INT DEFAULT NULL, visibiliter_id INT DEFAULT NULL, classe_id INT DEFAULT NULL, typologie_id INT DEFAULT NULL, presentoire_id INT DEFAULT NULL, quartier_id INT DEFAULT NULL, regie_tabac_id INT DEFAULT NULL, companie_oncour_id INT DEFAULT NULL, recette_id INT DEFAULT NULL, nbr_emplyer_id INT DEFAULT NULL, sheet_client_id INT DEFAULT NULL, decider_id INT DEFAULT NULL, code_client VARCHAR(255) DEFAULT NULL, licence VARCHAR(255) DEFAULT NULL, adress VARCHAR(255) DEFAULT NULL, recette_p VARCHAR(255) DEFAULT NULL, recette_s VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, info_acc_pdv TINYINT(1) DEFAULT NULL, date_signature VARCHAR(255) DEFAULT NULL, date_rappoort VARCHAR(255) DEFAULT NULL, date_instalation VARCHAR(255) DEFAULT NULL, is_tlp TINYINT(1) DEFAULT NULL, vendeur VARCHAR(255) DEFAULT NULL, jour_visite VARCHAR(255) DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, is_one_to_one TINYINT(1) DEFAULT NULL, is_fs_potentiel TINYINT(1) DEFAULT NULL, cin VARCHAR(255) DEFAULT NULL, num_licence VARCHAR(255) DEFAULT NULL, INDEX IDX_C7440455240A0569 (superficie_id), INDEX IDX_C7440455C4598A51 (emplacement_id), INDEX IDX_C7440455BAFB82A1 (environnement_id), INDEX IDX_C7440455FBA31A16 (type_de_quartier_id), INDEX IDX_C744045517D23694 (visibiliter_id), INDEX IDX_C74404558F5EA509 (classe_id), INDEX IDX_C744045542F4634A (typologie_id), INDEX IDX_C7440455F9D7ECED (presentoire_id), INDEX IDX_C7440455DF1E57AB (quartier_id), INDEX IDX_C744045570366793 (regie_tabac_id), INDEX IDX_C7440455BC85AEC0 (companie_oncour_id), INDEX IDX_C744045589312FE9 (recette_id), INDEX IDX_C744045584083435 (nbr_emplyer_id), INDEX IDX_C7440455255DD143 (sheet_client_id), INDEX IDX_C7440455F7B967BD (decider_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client_produit (client_id INT NOT NULL, produit_id INT NOT NULL, INDEX IDX_7B98A85A19EB6921 (client_id), INDEX IDX_7B98A85AF347EFB (produit_id), PRIMARY KEY(client_id, produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client_mini_report (id INT AUTO_INCREMENT NOT NULL, date DATETIME NOT NULL, merch_id INT NOT NULL, client_id INT NOT NULL, status VARCHAR(255) NOT NULL, closed_reason VARCHAR(255) NOT NULL, num_cycle INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client_state (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client_state_by_cycle_by_day (id INT AUTO_INCREMENT NOT NULL, client_id INT NOT NULL, etat_id INT NOT NULL, one_planning_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commentaire (id INT AUTO_INCREMENT NOT NULL, text LONGTEXT NOT NULL, type_commentaire VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cycle (id INT AUTO_INCREMENT NOT NULL, date_debut DATETIME NOT NULL, date_fin DATETIME NOT NULL, num_cycle INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE deligation (id INT AUTO_INCREMENT NOT NULL, gouvernorat_id INT NOT NULL, label VARCHAR(255) NOT NULL, INDEX IDX_EE8F291975B74E2D (gouvernorat_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE desinstallation_presentoire_not_jti (id INT AUTO_INCREMENT NOT NULL, is_desinstall TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE desinstallation_presentoire_not_jti_pdv_presentoire (desinstallation_presentoire_not_jti_id INT NOT NULL, pdv_presentoire_id INT NOT NULL, INDEX IDX_F7EA2CCEF13C5D0A (desinstallation_presentoire_not_jti_id), INDEX IDX_F7EA2CCED01443BC (pdv_presentoire_id), PRIMARY KEY(desinstallation_presentoire_not_jti_id, pdv_presentoire_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE des_install_presentoire_jti (id INT AUTO_INCREMENT NOT NULL, presentoire_id INT DEFAULT NULL, is_desinstall TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, INDEX IDX_B8BD3BDAF9D7ECED (presentoire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, date_creation DATETIME NOT NULL, classment VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE global_planning (id INT AUTO_INCREMENT NOT NULL, day1 INT DEFAULT NULL, day2 INT DEFAULT NULL, day3 INT DEFAULT NULL, day4 INT DEFAULT NULL, day5 INT DEFAULT NULL, day6 INT DEFAULT NULL, day7 INT DEFAULT NULL, day8 INT DEFAULT NULL, day9 INT DEFAULT NULL, day10 INT DEFAULT NULL, day11 INT DEFAULT NULL, day12 INT DEFAULT NULL, day13 INT DEFAULT NULL, merch_id INT NOT NULL, num_cycle INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gouvernorat (id INT AUTO_INCREMENT NOT NULL, zone_id INT NOT NULL, label VARCHAR(255) NOT NULL, INDEX IDX_4457C12B9F2C3FAB (zone_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE info_client (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, type_client_new_id INT DEFAULT NULL, situation_famil_id INT DEFAULT NULL, age_client_id INT DEFAULT NULL, nbr_enfant_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, INDEX IDX_A995B0319EB6921 (client_id), INDEX IDX_A995B03984D4F35 (type_client_new_id), INDEX IDX_A995B03E45A8B0F (situation_famil_id), INDEX IDX_A995B0316A55AEE (age_client_id), INDEX IDX_A995B03725D658B (nbr_enfant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE install_presentoire_jti (id INT AUTO_INCREMENT NOT NULL, presentoire_id INT DEFAULT NULL, is_installation TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, INDEX IDX_F5B1F655F9D7ECED (presentoire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE marketing_campagne_en_cours (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE marketing_recette (id INT AUTO_INCREMENT NOT NULL, recette_list VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE marketing_regie_tabac (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE merch (id INT AUTO_INCREMENT NOT NULL, region_id INT DEFAULT NULL, file_id INT DEFAULT NULL, code INT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, password_encrypted VARCHAR(255) NOT NULL, roles JSON DEFAULT NULL, UNIQUE INDEX UNIQ_F1B42EE077153098 (code), INDEX IDX_F1B42EE098260155 (region_id), UNIQUE INDEX UNIQ_F1B42EE093CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nbr_employer (id INT AUTO_INCREMENT NOT NULL, nbremployer VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE nbr_enfant (id INT AUTO_INCREMENT NOT NULL, nbr_enfant VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, visibility INT NOT NULL, text LONGTEXT NOT NULL, cycle_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification_merch (notification_id INT NOT NULL, merch_id INT NOT NULL, INDEX IDX_3700CB19EF1A9D84 (notification_id), INDEX IDX_3700CB198A86BD8 (merch_id), PRIMARY KEY(notification_id, merch_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE one_planning (id INT AUTO_INCREMENT NOT NULL, merch_id INT NOT NULL, cycle_id INT NOT NULL, date DATETIME DEFAULT NULL, a INT DEFAULT NULL, am INT DEFAULT NULL, classment VARCHAR(255) NOT NULL, INDEX IDX_82FA9248A86BD8 (merch_id), INDEX IDX_82FA9245EC1162 (cycle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operateur (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, telephone VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_classes (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_emplacements (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_environnements (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_ppsom (id INT AUTO_INCREMENT NOT NULL, ppsom VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_presentoire (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, label VARCHAR(255) NOT NULL, is_jti TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_CB0538AD3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_raison (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_shop (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, shop VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_5C9D03773DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_superficie (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_tposm (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_239C7B573DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_types_quartier (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_typologies (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pdv_visibilite (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE plv_temporaire (id INT AUTO_INCREMENT NOT NULL, quantiter_type_plv_id INT DEFAULT NULL, is_temporaire TINYINT(1) DEFAULT NULL, INDEX IDX_5F81C0D3CA6A400E (quantiter_type_plv_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE plv_temporaire_type_plv (plv_temporaire_id INT NOT NULL, type_plv_id INT NOT NULL, INDEX IDX_73DC83CEB8CB2AFE (plv_temporaire_id), INDEX IDX_73DC83CE12A1BE74 (type_plv_id), PRIMARY KEY(plv_temporaire_id, type_plv_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE praisontoir_maison_de_maire (id INT AUTO_INCREMENT NOT NULL, maison_de_maire VARCHAR(255) DEFAULT NULL, is_jti TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_ppsom_jti (id INT AUTO_INCREMENT NOT NULL, is_present TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_ppsom_jti_pdv_ppsom (presence_ppsom_jti_id INT NOT NULL, pdv_ppsom_id INT NOT NULL, INDEX IDX_16756D2051CE6127 (presence_ppsom_jti_id), INDEX IDX_16756D206F8E34ED (pdv_ppsom_id), PRIMARY KEY(presence_ppsom_jti_id, pdv_ppsom_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_presentoire_jti (id INT AUTO_INCREMENT NOT NULL, pdv_presentoire_id INT DEFAULT NULL, is_present TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, INDEX IDX_255332CCD01443BC (pdv_presentoire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_presentoire_jti_raison_presontoire (presence_presentoire_jti_id INT NOT NULL, raison_presontoire_id INT NOT NULL, INDEX IDX_26F582A9E1E6FE0E (presence_presentoire_jti_id), INDEX IDX_26F582A918B40618 (raison_presontoire_id), PRIMARY KEY(presence_presentoire_jti_id, raison_presontoire_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_presentoire_not_jti (id INT AUTO_INCREMENT NOT NULL, is_present TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_presentoire_not_jti_pdv_presentoire (presence_presentoire_not_jti_id INT NOT NULL, pdv_presentoire_id INT NOT NULL, INDEX IDX_98562021587269DA (presence_presentoire_not_jti_id), INDEX IDX_98562021D01443BC (pdv_presentoire_id), PRIMARY KEY(presence_presentoire_not_jti_id, pdv_presentoire_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_shop_jti (id INT AUTO_INCREMENT NOT NULL, is_present TINYINT(1) DEFAULT NULL, quantiter INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE presence_shop_jti_pdv_shop (presence_shop_jti_id INT NOT NULL, pdv_shop_id INT NOT NULL, INDEX IDX_59713BE79C5CA8A2 (presence_shop_jti_id), INDEX IDX_59713BE7926C0783 (pdv_shop_id), PRIMARY KEY(presence_shop_jti_id, pdv_shop_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit (id INT AUTO_INCREMENT NOT NULL, typeproduit_id INT DEFAULT NULL, file_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, stoke INT NOT NULL, INDEX IDX_29A5EC27F66E9EF6 (typeproduit_id), UNIQUE INDEX UNIQ_29A5EC2793CB796C (file_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quantiter_type_plv (id INT AUTO_INCREMENT NOT NULL, quantiter INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE quartier (id INT AUTO_INCREMENT NOT NULL, deligation_id INT NOT NULL, label VARCHAR(255) NOT NULL, INDEX IDX_FEE8962D4CF75C7B (deligation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE raison_presontoire (id INT AUTO_INCREMENT NOT NULL, raison VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_pposm (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, merch_id INT DEFAULT NULL, install_presentoire_jti_id INT DEFAULT NULL, des_install_presentoire_jti_id INT DEFAULT NULL, presence_presentoire_jti_id INT DEFAULT NULL, date_rapport DATETIME NOT NULL, INDEX IDX_67155D19EB6921 (client_id), INDEX IDX_67155D8A86BD8 (merch_id), INDEX IDX_67155DF2B6ECBF (install_presentoire_jti_id), INDEX IDX_67155D6F3D5567 (des_install_presentoire_jti_id), INDEX IDX_67155DE1E6FE0E (presence_presentoire_jti_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_pposm_presence_ppsom_jti (rapport_pposm_id INT NOT NULL, presence_ppsom_jti_id INT NOT NULL, INDEX IDX_60103FFDE6466A3C (rapport_pposm_id), INDEX IDX_60103FFD51CE6127 (presence_ppsom_jti_id), PRIMARY KEY(rapport_pposm_id, presence_ppsom_jti_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_pposm_presence_shop_jti (rapport_pposm_id INT NOT NULL, presence_shop_jti_id INT NOT NULL, INDEX IDX_2C040B7EE6466A3C (rapport_pposm_id), INDEX IDX_2C040B7E9C5CA8A2 (presence_shop_jti_id), PRIMARY KEY(rapport_pposm_id, presence_shop_jti_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_pposm_presence_presentoire_not_jti (rapport_pposm_id INT NOT NULL, presence_presentoire_not_jti_id INT NOT NULL, INDEX IDX_D116B7FFE6466A3C (rapport_pposm_id), INDEX IDX_D116B7FF587269DA (presence_presentoire_not_jti_id), PRIMARY KEY(rapport_pposm_id, presence_presentoire_not_jti_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_pposm_plv_temporaire (rapport_pposm_id INT NOT NULL, plv_temporaire_id INT NOT NULL, INDEX IDX_60FE8565E6466A3C (rapport_pposm_id), INDEX IDX_60FE8565B8CB2AFE (plv_temporaire_id), PRIMARY KEY(rapport_pposm_id, plv_temporaire_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_pposm_desinstallation_presentoire_not_jti (rapport_pposm_id INT NOT NULL, desinstallation_presentoire_not_jti_id INT NOT NULL, INDEX IDX_158846C5E6466A3C (rapport_pposm_id), INDEX IDX_158846C5F13C5D0A (desinstallation_presentoire_not_jti_id), PRIMARY KEY(rapport_pposm_id, desinstallation_presentoire_not_jti_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_produit (id INT AUTO_INCREMENT NOT NULL, is_dispo TINYINT(1) NOT NULL, is_veder TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_produit_produit (rapport_produit_id INT NOT NULL, produit_id INT NOT NULL, INDEX IDX_A6B04112A68BB28A (rapport_produit_id), INDEX IDX_A6B04112F347EFB (produit_id), PRIMARY KEY(rapport_produit_id, produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_tlp (id INT AUTO_INCREMENT NOT NULL, is_planogramme TINYINT(1) NOT NULL, is_eclairage TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_tlp_tlp_stoke_courant (rapport_tlp_id INT NOT NULL, tlp_stoke_courant_id INT NOT NULL, INDEX IDX_1A21719BEEC7054C (rapport_tlp_id), INDEX IDX_1A21719BECB2BF95 (tlp_stoke_courant_id), PRIMARY KEY(rapport_tlp_id, tlp_stoke_courant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rapport_tposm (id INT AUTO_INCREMENT NOT NULL, presence_nbr_article_id INT DEFAULT NULL, installation_nbr_id INT DEFAULT NULL, instalation_raison_id INT DEFAULT NULL, is_present TINYINT(1) NOT NULL, is_install TINYINT(1) NOT NULL, INDEX IDX_F5E7B39DB6BCA7AF (presence_nbr_article_id), INDEX IDX_F5E7B39DAE1EE8A8 (installation_nbr_id), INDEX IDX_F5E7B39D448D9A23 (instalation_raison_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, label VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE routing (id INT AUTO_INCREMENT NOT NULL, zone_id INT DEFAULT NULL, merch_id INT DEFAULT NULL, classe VARCHAR(255) NOT NULL, code_routing INT NOT NULL, ville VARCHAR(255) NOT NULL, information LONGTEXT NOT NULL, nbrs_pdv INT NOT NULL, INDEX IDX_A5F8B9FA9F2C3FAB (zone_id), UNIQUE INDEX UNIQ_A5F8B9FA8A86BD8 (merch_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE routing_client (routing_id INT NOT NULL, client_id INT NOT NULL, INDEX IDX_C14D365758735C4C (routing_id), INDEX IDX_C14D365719EB6921 (client_id), PRIMARY KEY(routing_id, client_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE situation_familialle (id INT AUTO_INCREMENT NOT NULL, sitation VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stoke_sheet (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, client_id INT DEFAULT NULL, stoke_sheet VARCHAR(255) DEFAULT NULL, INDEX IDX_98F6EDFBF347EFB (produit_id), INDEX IDX_98F6EDFB19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, cycle INT DEFAULT NULL, visibility INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_merch (survey_id INT NOT NULL, merch_id INT NOT NULL, INDEX IDX_FDC4DCD8B3FE509D (survey_id), INDEX IDX_FDC4DCD88A86BD8 (merch_id), PRIMARY KEY(survey_id, merch_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_questions (id INT AUTO_INCREMENT NOT NULL, survey_id INT NOT NULL, questions LONGTEXT NOT NULL, form_types VARCHAR(255) NOT NULL, options LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', INDEX IDX_2F8A16F8B3FE509D (survey_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE survey_report (id INT AUTO_INCREMENT NOT NULL, responses LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', merch_id INT NOT NULL, survey_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tlp (id INT AUTO_INCREMENT NOT NULL, planogramme TINYINT(1) NOT NULL, eclairage TINYINT(1) NOT NULL, score INT NOT NULL, bonus INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tlp_stoke_courant (id INT AUTO_INCREMENT NOT NULL, quantiter INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tposm_instalation_nbr (id INT AUTO_INCREMENT NOT NULL, nbr_article INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tposm_presence_nbr (id INT AUTO_INCREMENT NOT NULL, nbr_article INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE tposm_raison_refus (id INT AUTO_INCREMENT NOT NULL, raison VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_client (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_plv (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_produit (id INT AUTO_INCREMENT NOT NULL, type VARCHAR(255) NOT NULL, is_jti TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, user_name_admin VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, roles JSON DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE zone (id INT AUTO_INCREMENT NOT NULL, region_id INT NOT NULL, label VARCHAR(255) NOT NULL, INDEX IDX_A0EBC00798260155 (region_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455240A0569 FOREIGN KEY (superficie_id) REFERENCES pdv_superficie (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455C4598A51 FOREIGN KEY (emplacement_id) REFERENCES pdv_emplacements (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455BAFB82A1 FOREIGN KEY (environnement_id) REFERENCES pdv_environnements (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455FBA31A16 FOREIGN KEY (type_de_quartier_id) REFERENCES pdv_types_quartier (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045517D23694 FOREIGN KEY (visibiliter_id) REFERENCES pdv_visibilite (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C74404558F5EA509 FOREIGN KEY (classe_id) REFERENCES pdv_classes (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045542F4634A FOREIGN KEY (typologie_id) REFERENCES pdv_typologies (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455F9D7ECED FOREIGN KEY (presentoire_id) REFERENCES pdv_presentoire (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455DF1E57AB FOREIGN KEY (quartier_id) REFERENCES quartier (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045570366793 FOREIGN KEY (regie_tabac_id) REFERENCES marketing_regie_tabac (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455BC85AEC0 FOREIGN KEY (companie_oncour_id) REFERENCES marketing_campagne_en_cours (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045589312FE9 FOREIGN KEY (recette_id) REFERENCES marketing_recette (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045584083435 FOREIGN KEY (nbr_emplyer_id) REFERENCES nbr_employer (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455255DD143 FOREIGN KEY (sheet_client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455F7B967BD FOREIGN KEY (decider_id) REFERENCES type_client (id)');
        $this->addSql('ALTER TABLE client_produit ADD CONSTRAINT FK_7B98A85A19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE client_produit ADD CONSTRAINT FK_7B98A85AF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE deligation ADD CONSTRAINT FK_EE8F291975B74E2D FOREIGN KEY (gouvernorat_id) REFERENCES gouvernorat (id)');
        $this->addSql('ALTER TABLE desinstallation_presentoire_not_jti_pdv_presentoire ADD CONSTRAINT FK_F7EA2CCEF13C5D0A FOREIGN KEY (desinstallation_presentoire_not_jti_id) REFERENCES desinstallation_presentoire_not_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE desinstallation_presentoire_not_jti_pdv_presentoire ADD CONSTRAINT FK_F7EA2CCED01443BC FOREIGN KEY (pdv_presentoire_id) REFERENCES pdv_presentoire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE des_install_presentoire_jti ADD CONSTRAINT FK_B8BD3BDAF9D7ECED FOREIGN KEY (presentoire_id) REFERENCES pdv_presentoire (id)');
        $this->addSql('ALTER TABLE gouvernorat ADD CONSTRAINT FK_4457C12B9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        $this->addSql('ALTER TABLE info_client ADD CONSTRAINT FK_A995B0319EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE info_client ADD CONSTRAINT FK_A995B03984D4F35 FOREIGN KEY (type_client_new_id) REFERENCES type_client (id)');
        $this->addSql('ALTER TABLE info_client ADD CONSTRAINT FK_A995B03E45A8B0F FOREIGN KEY (situation_famil_id) REFERENCES situation_familialle (id)');
        $this->addSql('ALTER TABLE info_client ADD CONSTRAINT FK_A995B0316A55AEE FOREIGN KEY (age_client_id) REFERENCES age (id)');
        $this->addSql('ALTER TABLE info_client ADD CONSTRAINT FK_A995B03725D658B FOREIGN KEY (nbr_enfant_id) REFERENCES nbr_enfant (id)');
        $this->addSql('ALTER TABLE install_presentoire_jti ADD CONSTRAINT FK_F5B1F655F9D7ECED FOREIGN KEY (presentoire_id) REFERENCES pdv_presentoire (id)');
        $this->addSql('ALTER TABLE merch ADD CONSTRAINT FK_F1B42EE098260155 FOREIGN KEY (region_id) REFERENCES region (id)');
        $this->addSql('ALTER TABLE merch ADD CONSTRAINT FK_F1B42EE093CB796C FOREIGN KEY (file_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE notification_merch ADD CONSTRAINT FK_3700CB19EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification_merch ADD CONSTRAINT FK_3700CB198A86BD8 FOREIGN KEY (merch_id) REFERENCES merch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE one_planning ADD CONSTRAINT FK_82FA9248A86BD8 FOREIGN KEY (merch_id) REFERENCES merch (id)');
        $this->addSql('ALTER TABLE one_planning ADD CONSTRAINT FK_82FA9245EC1162 FOREIGN KEY (cycle_id) REFERENCES cycle (id)');
        $this->addSql('ALTER TABLE pdv_presentoire ADD CONSTRAINT FK_CB0538AD3DA5256D FOREIGN KEY (image_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE pdv_shop ADD CONSTRAINT FK_5C9D03773DA5256D FOREIGN KEY (image_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE pdv_tposm ADD CONSTRAINT FK_239C7B573DA5256D FOREIGN KEY (image_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE plv_temporaire ADD CONSTRAINT FK_5F81C0D3CA6A400E FOREIGN KEY (quantiter_type_plv_id) REFERENCES quantiter_type_plv (id)');
        $this->addSql('ALTER TABLE plv_temporaire_type_plv ADD CONSTRAINT FK_73DC83CEB8CB2AFE FOREIGN KEY (plv_temporaire_id) REFERENCES plv_temporaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plv_temporaire_type_plv ADD CONSTRAINT FK_73DC83CE12A1BE74 FOREIGN KEY (type_plv_id) REFERENCES type_plv (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_ppsom_jti_pdv_ppsom ADD CONSTRAINT FK_16756D2051CE6127 FOREIGN KEY (presence_ppsom_jti_id) REFERENCES presence_ppsom_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_ppsom_jti_pdv_ppsom ADD CONSTRAINT FK_16756D206F8E34ED FOREIGN KEY (pdv_ppsom_id) REFERENCES pdv_ppsom (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_presentoire_jti ADD CONSTRAINT FK_255332CCD01443BC FOREIGN KEY (pdv_presentoire_id) REFERENCES pdv_presentoire (id)');
        $this->addSql('ALTER TABLE presence_presentoire_jti_raison_presontoire ADD CONSTRAINT FK_26F582A9E1E6FE0E FOREIGN KEY (presence_presentoire_jti_id) REFERENCES presence_presentoire_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_presentoire_jti_raison_presontoire ADD CONSTRAINT FK_26F582A918B40618 FOREIGN KEY (raison_presontoire_id) REFERENCES raison_presontoire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_presentoire_not_jti_pdv_presentoire ADD CONSTRAINT FK_98562021587269DA FOREIGN KEY (presence_presentoire_not_jti_id) REFERENCES presence_presentoire_not_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_presentoire_not_jti_pdv_presentoire ADD CONSTRAINT FK_98562021D01443BC FOREIGN KEY (pdv_presentoire_id) REFERENCES pdv_presentoire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_shop_jti_pdv_shop ADD CONSTRAINT FK_59713BE79C5CA8A2 FOREIGN KEY (presence_shop_jti_id) REFERENCES presence_shop_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE presence_shop_jti_pdv_shop ADD CONSTRAINT FK_59713BE7926C0783 FOREIGN KEY (pdv_shop_id) REFERENCES pdv_shop (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27F66E9EF6 FOREIGN KEY (typeproduit_id) REFERENCES type_produit (id)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC2793CB796C FOREIGN KEY (file_id) REFERENCES file (id)');
        $this->addSql('ALTER TABLE quartier ADD CONSTRAINT FK_FEE8962D4CF75C7B FOREIGN KEY (deligation_id) REFERENCES deligation (id)');
        $this->addSql('ALTER TABLE rapport_pposm ADD CONSTRAINT FK_67155D19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE rapport_pposm ADD CONSTRAINT FK_67155D8A86BD8 FOREIGN KEY (merch_id) REFERENCES merch (id)');
        $this->addSql('ALTER TABLE rapport_pposm ADD CONSTRAINT FK_67155DF2B6ECBF FOREIGN KEY (install_presentoire_jti_id) REFERENCES install_presentoire_jti (id)');
        $this->addSql('ALTER TABLE rapport_pposm ADD CONSTRAINT FK_67155D6F3D5567 FOREIGN KEY (des_install_presentoire_jti_id) REFERENCES des_install_presentoire_jti (id)');
        $this->addSql('ALTER TABLE rapport_pposm ADD CONSTRAINT FK_67155DE1E6FE0E FOREIGN KEY (presence_presentoire_jti_id) REFERENCES presence_presentoire_jti (id)');
        $this->addSql('ALTER TABLE rapport_pposm_presence_ppsom_jti ADD CONSTRAINT FK_60103FFDE6466A3C FOREIGN KEY (rapport_pposm_id) REFERENCES rapport_pposm (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_presence_ppsom_jti ADD CONSTRAINT FK_60103FFD51CE6127 FOREIGN KEY (presence_ppsom_jti_id) REFERENCES presence_ppsom_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_presence_shop_jti ADD CONSTRAINT FK_2C040B7EE6466A3C FOREIGN KEY (rapport_pposm_id) REFERENCES rapport_pposm (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_presence_shop_jti ADD CONSTRAINT FK_2C040B7E9C5CA8A2 FOREIGN KEY (presence_shop_jti_id) REFERENCES presence_shop_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_presence_presentoire_not_jti ADD CONSTRAINT FK_D116B7FFE6466A3C FOREIGN KEY (rapport_pposm_id) REFERENCES rapport_pposm (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_presence_presentoire_not_jti ADD CONSTRAINT FK_D116B7FF587269DA FOREIGN KEY (presence_presentoire_not_jti_id) REFERENCES presence_presentoire_not_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_plv_temporaire ADD CONSTRAINT FK_60FE8565E6466A3C FOREIGN KEY (rapport_pposm_id) REFERENCES rapport_pposm (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_plv_temporaire ADD CONSTRAINT FK_60FE8565B8CB2AFE FOREIGN KEY (plv_temporaire_id) REFERENCES plv_temporaire (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_desinstallation_presentoire_not_jti ADD CONSTRAINT FK_158846C5E6466A3C FOREIGN KEY (rapport_pposm_id) REFERENCES rapport_pposm (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_pposm_desinstallation_presentoire_not_jti ADD CONSTRAINT FK_158846C5F13C5D0A FOREIGN KEY (desinstallation_presentoire_not_jti_id) REFERENCES desinstallation_presentoire_not_jti (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_produit_produit ADD CONSTRAINT FK_A6B04112A68BB28A FOREIGN KEY (rapport_produit_id) REFERENCES rapport_produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_produit_produit ADD CONSTRAINT FK_A6B04112F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_tlp_tlp_stoke_courant ADD CONSTRAINT FK_1A21719BEEC7054C FOREIGN KEY (rapport_tlp_id) REFERENCES rapport_tlp (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_tlp_tlp_stoke_courant ADD CONSTRAINT FK_1A21719BECB2BF95 FOREIGN KEY (tlp_stoke_courant_id) REFERENCES tlp_stoke_courant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rapport_tposm ADD CONSTRAINT FK_F5E7B39DB6BCA7AF FOREIGN KEY (presence_nbr_article_id) REFERENCES tposm_presence_nbr (id)');
        $this->addSql('ALTER TABLE rapport_tposm ADD CONSTRAINT FK_F5E7B39DAE1EE8A8 FOREIGN KEY (installation_nbr_id) REFERENCES tposm_instalation_nbr (id)');
        $this->addSql('ALTER TABLE rapport_tposm ADD CONSTRAINT FK_F5E7B39D448D9A23 FOREIGN KEY (instalation_raison_id) REFERENCES tposm_raison_refus (id)');
        $this->addSql('ALTER TABLE routing ADD CONSTRAINT FK_A5F8B9FA9F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        $this->addSql('ALTER TABLE routing ADD CONSTRAINT FK_A5F8B9FA8A86BD8 FOREIGN KEY (merch_id) REFERENCES merch (id)');
        $this->addSql('ALTER TABLE routing_client ADD CONSTRAINT FK_C14D365758735C4C FOREIGN KEY (routing_id) REFERENCES routing (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE routing_client ADD CONSTRAINT FK_C14D365719EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stoke_sheet ADD CONSTRAINT FK_98F6EDFBF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE stoke_sheet ADD CONSTRAINT FK_98F6EDFB19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE survey_merch ADD CONSTRAINT FK_FDC4DCD8B3FE509D FOREIGN KEY (survey_id) REFERENCES survey (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE survey_merch ADD CONSTRAINT FK_FDC4DCD88A86BD8 FOREIGN KEY (merch_id) REFERENCES merch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE survey_questions ADD CONSTRAINT FK_2F8A16F8B3FE509D FOREIGN KEY (survey_id) REFERENCES survey (id)');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC00798260155 FOREIGN KEY (region_id) REFERENCES region (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE info_client DROP FOREIGN KEY FK_A995B0316A55AEE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455255DD143');
        $this->addSql('ALTER TABLE client_produit DROP FOREIGN KEY FK_7B98A85A19EB6921');
        $this->addSql('ALTER TABLE info_client DROP FOREIGN KEY FK_A995B0319EB6921');
        $this->addSql('ALTER TABLE rapport_pposm DROP FOREIGN KEY FK_67155D19EB6921');
        $this->addSql('ALTER TABLE routing_client DROP FOREIGN KEY FK_C14D365719EB6921');
        $this->addSql('ALTER TABLE stoke_sheet DROP FOREIGN KEY FK_98F6EDFB19EB6921');
        $this->addSql('ALTER TABLE one_planning DROP FOREIGN KEY FK_82FA9245EC1162');
        $this->addSql('ALTER TABLE quartier DROP FOREIGN KEY FK_FEE8962D4CF75C7B');
        $this->addSql('ALTER TABLE desinstallation_presentoire_not_jti_pdv_presentoire DROP FOREIGN KEY FK_F7EA2CCEF13C5D0A');
        $this->addSql('ALTER TABLE rapport_pposm_desinstallation_presentoire_not_jti DROP FOREIGN KEY FK_158846C5F13C5D0A');
        $this->addSql('ALTER TABLE rapport_pposm DROP FOREIGN KEY FK_67155D6F3D5567');
        $this->addSql('ALTER TABLE merch DROP FOREIGN KEY FK_F1B42EE093CB796C');
        $this->addSql('ALTER TABLE pdv_presentoire DROP FOREIGN KEY FK_CB0538AD3DA5256D');
        $this->addSql('ALTER TABLE pdv_shop DROP FOREIGN KEY FK_5C9D03773DA5256D');
        $this->addSql('ALTER TABLE pdv_tposm DROP FOREIGN KEY FK_239C7B573DA5256D');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC2793CB796C');
        $this->addSql('ALTER TABLE deligation DROP FOREIGN KEY FK_EE8F291975B74E2D');
        $this->addSql('ALTER TABLE rapport_pposm DROP FOREIGN KEY FK_67155DF2B6ECBF');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455BC85AEC0');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045589312FE9');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045570366793');
        $this->addSql('ALTER TABLE notification_merch DROP FOREIGN KEY FK_3700CB198A86BD8');
        $this->addSql('ALTER TABLE one_planning DROP FOREIGN KEY FK_82FA9248A86BD8');
        $this->addSql('ALTER TABLE rapport_pposm DROP FOREIGN KEY FK_67155D8A86BD8');
        $this->addSql('ALTER TABLE routing DROP FOREIGN KEY FK_A5F8B9FA8A86BD8');
        $this->addSql('ALTER TABLE survey_merch DROP FOREIGN KEY FK_FDC4DCD88A86BD8');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045584083435');
        $this->addSql('ALTER TABLE info_client DROP FOREIGN KEY FK_A995B03725D658B');
        $this->addSql('ALTER TABLE notification_merch DROP FOREIGN KEY FK_3700CB19EF1A9D84');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C74404558F5EA509');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455C4598A51');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455BAFB82A1');
        $this->addSql('ALTER TABLE presence_ppsom_jti_pdv_ppsom DROP FOREIGN KEY FK_16756D206F8E34ED');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455F9D7ECED');
        $this->addSql('ALTER TABLE desinstallation_presentoire_not_jti_pdv_presentoire DROP FOREIGN KEY FK_F7EA2CCED01443BC');
        $this->addSql('ALTER TABLE des_install_presentoire_jti DROP FOREIGN KEY FK_B8BD3BDAF9D7ECED');
        $this->addSql('ALTER TABLE install_presentoire_jti DROP FOREIGN KEY FK_F5B1F655F9D7ECED');
        $this->addSql('ALTER TABLE presence_presentoire_jti DROP FOREIGN KEY FK_255332CCD01443BC');
        $this->addSql('ALTER TABLE presence_presentoire_not_jti_pdv_presentoire DROP FOREIGN KEY FK_98562021D01443BC');
        $this->addSql('ALTER TABLE presence_shop_jti_pdv_shop DROP FOREIGN KEY FK_59713BE7926C0783');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455240A0569');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455FBA31A16');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045542F4634A');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045517D23694');
        $this->addSql('ALTER TABLE plv_temporaire_type_plv DROP FOREIGN KEY FK_73DC83CEB8CB2AFE');
        $this->addSql('ALTER TABLE rapport_pposm_plv_temporaire DROP FOREIGN KEY FK_60FE8565B8CB2AFE');
        $this->addSql('ALTER TABLE presence_ppsom_jti_pdv_ppsom DROP FOREIGN KEY FK_16756D2051CE6127');
        $this->addSql('ALTER TABLE rapport_pposm_presence_ppsom_jti DROP FOREIGN KEY FK_60103FFD51CE6127');
        $this->addSql('ALTER TABLE presence_presentoire_jti_raison_presontoire DROP FOREIGN KEY FK_26F582A9E1E6FE0E');
        $this->addSql('ALTER TABLE rapport_pposm DROP FOREIGN KEY FK_67155DE1E6FE0E');
        $this->addSql('ALTER TABLE presence_presentoire_not_jti_pdv_presentoire DROP FOREIGN KEY FK_98562021587269DA');
        $this->addSql('ALTER TABLE rapport_pposm_presence_presentoire_not_jti DROP FOREIGN KEY FK_D116B7FF587269DA');
        $this->addSql('ALTER TABLE presence_shop_jti_pdv_shop DROP FOREIGN KEY FK_59713BE79C5CA8A2');
        $this->addSql('ALTER TABLE rapport_pposm_presence_shop_jti DROP FOREIGN KEY FK_2C040B7E9C5CA8A2');
        $this->addSql('ALTER TABLE client_produit DROP FOREIGN KEY FK_7B98A85AF347EFB');
        $this->addSql('ALTER TABLE rapport_produit_produit DROP FOREIGN KEY FK_A6B04112F347EFB');
        $this->addSql('ALTER TABLE stoke_sheet DROP FOREIGN KEY FK_98F6EDFBF347EFB');
        $this->addSql('ALTER TABLE plv_temporaire DROP FOREIGN KEY FK_5F81C0D3CA6A400E');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455DF1E57AB');
        $this->addSql('ALTER TABLE presence_presentoire_jti_raison_presontoire DROP FOREIGN KEY FK_26F582A918B40618');
        $this->addSql('ALTER TABLE rapport_pposm_presence_ppsom_jti DROP FOREIGN KEY FK_60103FFDE6466A3C');
        $this->addSql('ALTER TABLE rapport_pposm_presence_shop_jti DROP FOREIGN KEY FK_2C040B7EE6466A3C');
        $this->addSql('ALTER TABLE rapport_pposm_presence_presentoire_not_jti DROP FOREIGN KEY FK_D116B7FFE6466A3C');
        $this->addSql('ALTER TABLE rapport_pposm_plv_temporaire DROP FOREIGN KEY FK_60FE8565E6466A3C');
        $this->addSql('ALTER TABLE rapport_pposm_desinstallation_presentoire_not_jti DROP FOREIGN KEY FK_158846C5E6466A3C');
        $this->addSql('ALTER TABLE rapport_produit_produit DROP FOREIGN KEY FK_A6B04112A68BB28A');
        $this->addSql('ALTER TABLE rapport_tlp_tlp_stoke_courant DROP FOREIGN KEY FK_1A21719BEEC7054C');
        $this->addSql('ALTER TABLE merch DROP FOREIGN KEY FK_F1B42EE098260155');
        $this->addSql('ALTER TABLE zone DROP FOREIGN KEY FK_A0EBC00798260155');
        $this->addSql('ALTER TABLE routing_client DROP FOREIGN KEY FK_C14D365758735C4C');
        $this->addSql('ALTER TABLE info_client DROP FOREIGN KEY FK_A995B03E45A8B0F');
        $this->addSql('ALTER TABLE survey_merch DROP FOREIGN KEY FK_FDC4DCD8B3FE509D');
        $this->addSql('ALTER TABLE survey_questions DROP FOREIGN KEY FK_2F8A16F8B3FE509D');
        $this->addSql('ALTER TABLE rapport_tlp_tlp_stoke_courant DROP FOREIGN KEY FK_1A21719BECB2BF95');
        $this->addSql('ALTER TABLE rapport_tposm DROP FOREIGN KEY FK_F5E7B39DAE1EE8A8');
        $this->addSql('ALTER TABLE rapport_tposm DROP FOREIGN KEY FK_F5E7B39DB6BCA7AF');
        $this->addSql('ALTER TABLE rapport_tposm DROP FOREIGN KEY FK_F5E7B39D448D9A23');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455F7B967BD');
        $this->addSql('ALTER TABLE info_client DROP FOREIGN KEY FK_A995B03984D4F35');
        $this->addSql('ALTER TABLE plv_temporaire_type_plv DROP FOREIGN KEY FK_73DC83CE12A1BE74');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC27F66E9EF6');
        $this->addSql('ALTER TABLE gouvernorat DROP FOREIGN KEY FK_4457C12B9F2C3FAB');
        $this->addSql('ALTER TABLE routing DROP FOREIGN KEY FK_A5F8B9FA9F2C3FAB');
        $this->addSql('DROP TABLE age');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE client_produit');
        $this->addSql('DROP TABLE client_mini_report');
        $this->addSql('DROP TABLE client_state');
        $this->addSql('DROP TABLE client_state_by_cycle_by_day');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE cycle');
        $this->addSql('DROP TABLE deligation');
        $this->addSql('DROP TABLE desinstallation_presentoire_not_jti');
        $this->addSql('DROP TABLE desinstallation_presentoire_not_jti_pdv_presentoire');
        $this->addSql('DROP TABLE des_install_presentoire_jti');
        $this->addSql('DROP TABLE file');
        $this->addSql('DROP TABLE global_planning');
        $this->addSql('DROP TABLE gouvernorat');
        $this->addSql('DROP TABLE info_client');
        $this->addSql('DROP TABLE install_presentoire_jti');
        $this->addSql('DROP TABLE marketing_campagne_en_cours');
        $this->addSql('DROP TABLE marketing_recette');
        $this->addSql('DROP TABLE marketing_regie_tabac');
        $this->addSql('DROP TABLE merch');
        $this->addSql('DROP TABLE nbr_employer');
        $this->addSql('DROP TABLE nbr_enfant');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_merch');
        $this->addSql('DROP TABLE one_planning');
        $this->addSql('DROP TABLE operateur');
        $this->addSql('DROP TABLE pdv_classes');
        $this->addSql('DROP TABLE pdv_emplacements');
        $this->addSql('DROP TABLE pdv_environnements');
        $this->addSql('DROP TABLE pdv_ppsom');
        $this->addSql('DROP TABLE pdv_presentoire');
        $this->addSql('DROP TABLE pdv_raison');
        $this->addSql('DROP TABLE pdv_shop');
        $this->addSql('DROP TABLE pdv_superficie');
        $this->addSql('DROP TABLE pdv_tposm');
        $this->addSql('DROP TABLE pdv_types_quartier');
        $this->addSql('DROP TABLE pdv_typologies');
        $this->addSql('DROP TABLE pdv_visibilite');
        $this->addSql('DROP TABLE plv_temporaire');
        $this->addSql('DROP TABLE plv_temporaire_type_plv');
        $this->addSql('DROP TABLE praisontoir_maison_de_maire');
        $this->addSql('DROP TABLE presence_ppsom_jti');
        $this->addSql('DROP TABLE presence_ppsom_jti_pdv_ppsom');
        $this->addSql('DROP TABLE presence_presentoire_jti');
        $this->addSql('DROP TABLE presence_presentoire_jti_raison_presontoire');
        $this->addSql('DROP TABLE presence_presentoire_not_jti');
        $this->addSql('DROP TABLE presence_presentoire_not_jti_pdv_presentoire');
        $this->addSql('DROP TABLE presence_shop_jti');
        $this->addSql('DROP TABLE presence_shop_jti_pdv_shop');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE quantiter_type_plv');
        $this->addSql('DROP TABLE quartier');
        $this->addSql('DROP TABLE raison_presontoire');
        $this->addSql('DROP TABLE rapport_pposm');
        $this->addSql('DROP TABLE rapport_pposm_presence_ppsom_jti');
        $this->addSql('DROP TABLE rapport_pposm_presence_shop_jti');
        $this->addSql('DROP TABLE rapport_pposm_presence_presentoire_not_jti');
        $this->addSql('DROP TABLE rapport_pposm_plv_temporaire');
        $this->addSql('DROP TABLE rapport_pposm_desinstallation_presentoire_not_jti');
        $this->addSql('DROP TABLE rapport_produit');
        $this->addSql('DROP TABLE rapport_produit_produit');
        $this->addSql('DROP TABLE rapport_tlp');
        $this->addSql('DROP TABLE rapport_tlp_tlp_stoke_courant');
        $this->addSql('DROP TABLE rapport_tposm');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE routing');
        $this->addSql('DROP TABLE routing_client');
        $this->addSql('DROP TABLE situation_familialle');
        $this->addSql('DROP TABLE stoke_sheet');
        $this->addSql('DROP TABLE survey');
        $this->addSql('DROP TABLE survey_merch');
        $this->addSql('DROP TABLE survey_questions');
        $this->addSql('DROP TABLE survey_report');
        $this->addSql('DROP TABLE tlp');
        $this->addSql('DROP TABLE tlp_stoke_courant');
        $this->addSql('DROP TABLE tposm_instalation_nbr');
        $this->addSql('DROP TABLE tposm_presence_nbr');
        $this->addSql('DROP TABLE tposm_raison_refus');
        $this->addSql('DROP TABLE type_client');
        $this->addSql('DROP TABLE type_plv');
        $this->addSql('DROP TABLE type_produit');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE zone');
        $this->addSql('DROP TABLE refresh_tokens');
    }
}
